### ISSUE TITLE
Public link for players to claim drops

### ISSUE THREAD

**Issue by oolumorin** [moonstream-to/frontend#223]
# Goal
Have a public view for players to claim drops.

Currently, we have a public-facing view for leaderboards where players can check their rankings without the need for games to create a leaderboard page. We want to do something similar for Dropper by creating a claims page where players can log in with their wallet, see all the drops they can claim and claim these available drops.

# User flow
- User goes to claim site - moonstream.to/claims.
- Logs in with their wallet.
- Meta transaction API checks to see which drops have been assigned to them.
- User can see available and previously claimed drops (previously claimed drops are greyed out with the most recent displayed with "view all" to view all.
- User can claim available drops, which would become greyed out once claimed.

# Milestones

- [ ] Design claims page @ishihssihshihishsi 
- [ ] implement design @Anton-Mushnin 
- [ ] Test 
- [ ] Deploy to front end
- [ ] Announce feature @oolumorin
